apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # plural + "." + group
  name: databases.sample.felipe1496.github.com
spec:
  group: sample.felipe1496.github.com
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
    shortNames:
      - db
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                engine:
                  type: string
                  description: 'Ex: "postgres", "mysql"'
                version:
                  type: string
                storage:
                  type: string
              required:
                - engine
                - version
                - storage
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: 'Ex: "Ready", "Provisioning"'
      subresources:
        status: {}
